baseURL = 'https://blog.msansm1.bzh/'
title = 'Mon blog'
theme = 'ananke'
defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = true
sectionPagesMenu = "main"
enableRobotsTXT = true

[languages]
  [languages.fr]
    contentDir = 'content/fr'
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Fran√ßais'
    title = 'Blog de Msansm1'
    weight = 1
    [languages.fr.params]
      subtitle = 'Articles techniques'

  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Blog of Msansm1'
    weight = 2
    [languages.en.params]
      subtitle = 'Technical articles'


[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = "dark-gray"
author = ""
favicon = ""
site_logo = ""
description = "Mon blog perso avec des articles techniques"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-gray"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-20"
recent_posts_number = 3

[params.ananke.social.share]
networks = [
  "bluesky",
]

[params.ananke.social.follow]
networks = [
  "bluesky"
]

[params.ananke.social.bluesky]
username = "msansm1.bzh"